######################################################################
# Automatically generated by qmake (2.01a) Wt 1. wrz 19:41:11 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += D:/tmp/qt/madserver/. .
QT        += core network 

# Input
HEADERS += MadNet.h MadServer.h MadShooter.h MadWorker.h
SOURCES += MadNet.cpp MadServer.cpp MadShooter.cpp MadWorker.cpp main.cpp
