######################################################################
# Automatically generated by qmake (2.01a) ?r 2. wrz 14:17:40 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += D:/tmp/qt/madviewer/. .
CONFIG += CONSOLE qtestlib
QT += core network

# Input
HEADERS += MadViewer.h MadNet.h
SOURCES += MadViewer.cpp MadNet.cpp main.cpp

