######################################################################
# Automatically generated by qmake (2.01a) Pn 7. wrz 16:57:24 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += D:/tmp/qt/madviewer/. .
CONFIG += CONSOLE qtestlib
QT += core network

# Input
HEADERS += MadNet.h MadViewer.h
SOURCES += MadNet.cpp MadViewer.cpp main.cpp
