######################################################################
# Automatically generated by qmake (2.01a) Wt 1. wrz 19:42:36 2009
######################################################################
QT        += core network 
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += D:/tmp/qt/madviewer/. .

# Input
HEADERS += MadSocket.h
SOURCES += MadSocket.cpp main.cpp
